First Commit
kamilDzietczyk/invoicing-system-kamil-dzietczyk pull request #3
Opened 2023-06-26 10:54 UTC by kamilDzietczyk

First PullRequest

2023-07-11 12:04 UTC, BartoszKamyszek requested changes

2023-07-11 12:04 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/service/InvoiceService.java
> +  public Optional<Invoice> getById(int id) throws IOException {
powinno być łapane w bazie

2023-07-11 12:04 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/AppTest.groovy
>      }
dlaczego testujesz enuma w klasie AppTest?

2023-07-11 12:04 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/jsondatabase/JsonDatabaseTest.groovy
> +    private static Vat vat;
dlaczego wszystkie pola są statyczne?

2023-07-11 12:04 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/jsondatabase/JsonDatabaseTest.groovy
> +class JsonDatabaseTest extends Specification{
formatowanie coś nie zadziałało

2023-08-01 19:34 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/jsondatabase/ActualPath.java
> +  private String databasePath = basePath.resolve("database.json").toString();
lepiej trzymać takie dane jako stałe statyczne i wtedy bez tworzenia obiektu. Nie robisz na nim potem żadnych działań, a wszystkie dane są stałe, więc tworzenie jest bez sensu.

2023-08-01 19:36 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/jsondatabase/JsonService.java
> +  ObjectMapper objectMapper;
pole prywatne

2023-08-01 19:36 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/jsondatabase/JsonService.java
> +  public String json(Object object) {
nazwa średnia, metoda powinna mieć czasownik, więc convertToJson albo ewentualnie krócej toJson

2023-08-01 19:37 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/jsondatabase/JsonService.java
> +  public <T> T object(String json, Class<T> clazz) {
jak wyżej

2023-08-01 19:38 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/helpers/TestHelpers.groovy
> +}
jeżeli idziesz w tworzenie stałych obiektów, to nadaj im odpowiednie nazwy, buy i buy1 nie mówi mi absolutnie nic

2023-08-01 19:39 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/jsondatabase/JsonDatabaseTest.groovy
> +class JsonDatabaseTest extends Specification{
formatowanie dalej popsute

2023-08-01 19:41 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/jsondatabase/JsonDatabaseTest.groovy
> +    @Shared Vat vat = Vat.Vat_7
możesz też użyć metody setup do tworzenia takich obiektów

2023-08-01 19:44 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/jsondatabase/JsonService.java
> +public class JsonService {
brakuje testów

2023-08-01 19:44 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/jsondatabase/FileService.java
> +public class FileService {
brakuje testów

2023-09-02 16:10 UTC, merged

2023-09-02 16:11 UTC, kamilDzietczyk commented
Task_3